<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Atc.Cosmos.EventStore.Cqrs</PackageId>
    <PackageTags>event-store;cqrs;events;cosmos</PackageTags>
    <Description>CQRS implementation for Atc.Cosmos.EventStore</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Link="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <Using Remove="System.IO" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Atc.Cosmos.EventStore\Atc.Cosmos.EventStore.csproj" />
  </ItemGroup>

</Project>